
export const IMMEDIATE_EVENTS = 'IMMEDIATE_EVENTS';
export const SPORTING_EVENTS = 'SPORTING_EVENTS';
export const SEARCH_TERM = 'SEARCH_TERM';
export const EVENTS_BY_TEAM = 'EVENTS_BY_TEAM';
export const EVENTS_BY_ARTIST = 'EVENTS_BY_ARTIST';
export const ME_SET = 'ME_SET';
export const TRACKS_SET = 'TRACKS_SET';
export const INITIAL_PIECES = 'INITIAL_PIECES';
export const SET_CONTEMPLATED_PIECE = 'SET_CONTEMPLATED_PIECE';
export const REPLACE_INITIAL_PLAYLIST = 'REPLACE_INITIAL_PLAYLIST';
export const GET_ANCILLARY_PIECES = 'GET_ANCILLARY_PIECES';
export const ORGANIZE_PIECES = 'ORGANIZE_PIECES';
export const SHOW_USER = 'SHOW_USER';
export const ESTABLISH_BASIC_INFO = 'ESTABLISH_BASIC_INFO';
export const CONTACT_INFO = 'CONTACT_INFO';
export const ESTABLISH_GENDER = 'ESTABLISH_GENDER';